#!/usr/bin/env bash
# Regenerate src/fontin_data.inc — the Fontin faces embedded in the executable.
# Run this only when changing the bundled typeface; the output is committed.
#
# Needs the TTFs in assets/fonts (scripts/fetch-fonts.sh) and a configured build
# tree, for ImGui's binary_to_compressed_c.cpp.
set -euo pipefail

root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
fonts="$root/assets/fonts"
out="$root/src/fontin_data.inc"
imgui="${IMGUI_SOURCE_DIR:-$root/build/_deps/imgui-src}"

[ -f "$fonts/Fontin-Regular.ttf" ] || "$root/scripts/fetch-fonts.sh"
if [ ! -f "$imgui/misc/fonts/binary_to_compressed_c.cpp" ]; then
  echo "no ImGui source at $imgui — configure the build first, or set IMGUI_SOURCE_DIR" >&2
  exit 1
fi

tmp="$(mktemp -d)"
trap 'rm -rf "$tmp"' EXIT
c++ -O2 -o "$tmp/b2c" "$imgui/misc/fonts/binary_to_compressed_c.cpp"

{
  echo "// Generated by scripts/gen-font-data.sh — do not edit."
  echo "// Fontin by Jos Buivenga (exljbris), base85-encoded + stb_compress."
  echo "// See assets/fonts/README.md for the license this is bundled under."
  for face in Regular:regular Bold:bold Italic:italic SmallCaps:small_caps; do
    echo
    "$tmp/b2c" -base85 "$fonts/Fontin-${face%%:*}.ttf" "fontin_${face##*:}" | tail -n +3
  done
} > "$out"

echo "wrote $out ($(wc -c < "$out") bytes)"
