#!/usr/bin/env bash
# Regenerate the embedded application icon from assets/popc_icon.png:
#   src/icon_data.inc   — the PNG, base85-encoded (same idiom as the fonts)
#   assets/popc_icon.ico — the Windows executable resource
# Both outputs are committed; run this only when the artwork changes.
# Needs ImageMagick for the .ico.
set -euo pipefail

root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
src="$root/assets/popc_icon.png"
out="$root/src/icon_data.inc"
ico="$root/assets/popc_icon.ico"

[ -f "$src" ] || { echo "no icon at $src" >&2; exit 1; }

python3 - "$src" "$out" <<'PY'
import sys

src, out = sys.argv[1], sys.argv[2]
data = open(src, 'rb').read()
size = len(data)
padded = data + b'\0' * (-size % 4)  # the decoder works in 4-byte groups

def enc(v):
    v = v % 85 + 35
    return chr(v + 1 if v >= ord('\\') else v)  # backslash would escape the next char

chars = []
for i in range(0, len(padded), 4):
    word = int.from_bytes(padded[i:i+4], 'little')
    for _ in range(5):
        chars.append(enc(word))
        word //= 85

with open(out, 'w') as f:
    f.write("// Generated by scripts/gen-icon-data.sh from assets/popc_icon.png — do not edit.\n\n")
    f.write(f"static const unsigned int popc_icon_png_size = {size};\n")
    f.write(f"static const char popc_icon_png_base85[{len(chars)}+1] =\n")
    for i in range(0, len(chars), 120):
        # '\?' keeps a stray '??x' from being read as a trigraph (a warning, not an error).
        line = ''.join(chars[i:i+120]).replace('?', '\\?')
        f.write('    "%s"%s\n' % (line, ';' if i + 120 >= len(chars) else ''))
print(f"wrote {out} ({size} bytes of PNG -> {len(chars)} chars)")
PY

if command -v magick >/dev/null; then
  # No entry above the source's own 128px — upscaled sizes are just bloat.
  magick "$src" -define icon:auto-resize=128,64,48,32,16 "$ico"
  echo "wrote $ico"
else
  echo "ImageMagick not found — $ico left unchanged" >&2
fi
