#!/usr/bin/env bash
# Regenerate src/glyph_data.inc — the UI glyph font embedded in the executable.
# Run this only when changing which glyphs are bundled; the output is committed.
#
# Needs assets/fonts/PPCGlyphs.ttf (scripts/fetch-glyphs.sh) and a configured build
# tree, for ImGui's binary_to_compressed_c.cpp.
set -euo pipefail

root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
fonts="$root/assets/fonts"
out="$root/src/glyph_data.inc"
imgui="${IMGUI_SOURCE_DIR:-$root/build/_deps/imgui-src}"

[ -f "$fonts/PPCGlyphs.ttf" ] || "$root/scripts/fetch-glyphs.sh"
if [ ! -f "$imgui/misc/fonts/binary_to_compressed_c.cpp" ]; then
  echo "no ImGui source at $imgui — configure the build first, or set IMGUI_SOURCE_DIR" >&2
  exit 1
fi

tmp="$(mktemp -d)"
trap 'rm -rf "$tmp"' EXIT
c++ -O2 -o "$tmp/b2c" "$imgui/misc/fonts/binary_to_compressed_c.cpp"

{
  echo "// Generated by scripts/gen-glyph-data.sh — do not edit."
  echo "// A subset of Font Awesome Free Solid, base85-encoded + stb_compress."
  echo "// Which codepoints: scripts/fetch-glyphs.sh. What they are called: src/ui/glyphs.hpp."
  echo "// See assets/fonts/README.md for the license this is bundled under."
  echo
  "$tmp/b2c" -base85 "$fonts/PPCGlyphs.ttf" "ppc_glyphs" | tail -n +3
} > "$out"

echo "wrote $out ($(wc -c < "$out") bytes)"
