#!/usr/bin/env bash
# Regenerate the embedded application icon from assets/popc_icon.png:
#   src/icon_data.inc   — the PNG bytes, for the tray and the window icon
#   assets/popc_icon.ico — the Windows executable resource
# Both outputs are committed; run this only when the artwork changes. Needs ImageMagick.
#
# The embedded copy is downscaled first. It is only ever drawn at tray size — 16 or 32px on
# Windows, a little more under a GTK panel — and as the window icon a switcher may show larger,
# which is what 64 is for. The 128px master stays the source of the .ico, where the big entries
# are the ones Explorer actually uses.
set -euo pipefail

root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
src="$root/assets/popc_icon.png"
out="$root/src/icon_data.inc"
ico="$root/assets/popc_icon.ico"

[ -f "$src" ] || { echo "no icon at $src" >&2; exit 1; }
command -v magick >/dev/null || { echo "ImageMagick (magick) is required" >&2; exit 1; }

tmp="$(mktemp -d)"
trap 'rm -rf "$tmp"' EXIT
magick "$src" -resize 64x64 -strip "$tmp/icon64.png"

{
  echo "// Generated by scripts/gen-icon-data.sh from assets/popc_icon.png — do not edit."
  echo "// The 128px master downscaled to 64; the .ico resource is where the big sizes live."
  echo
  python3 "$root/scripts/bin2c.py" popc_icon_png "$tmp/icon64.png"
} > "$out"
echo "wrote $out ($(wc -c < "$tmp/icon64.png") bytes of PNG)"

# No entry above the source's own 128px — upscaled sizes are just bloat.
magick "$src" -define icon:auto-resize=128,64,48,32,16 "$ico"
echo "wrote $ico"
