#!/usr/bin/env bash
# Regenerate src/fontin_data.inc — the Fontin faces embedded in the executable.
# Run this only when changing the bundled typeface; the output is committed.
#
# Needs the TTFs in assets/fonts (scripts/fetch-fonts.sh). The faces go in as their own
# bytes — scripts/bin2c.py says why that is worth the few kilobytes.
set -euo pipefail

root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
fonts="$root/assets/fonts"
out="$root/src/fontin_data.inc"

[ -f "$fonts/Fontin-Regular.ttf" ] || "$root/scripts/fetch-fonts.sh"

{
  echo "// Generated by scripts/gen-font-data.sh — do not edit."
  echo "// Fontin by Jos Buivenga (exljbris), embedded as the TTF bytes themselves."
  echo "// See assets/fonts/README.md for the license this is bundled under."
  for face in Regular:regular Bold:bold Italic:italic SmallCaps:small_caps; do
    echo
    python3 "$root/scripts/bin2c.py" "fontin_${face##*:}_ttf" "$fonts/Fontin-${face%%:*}.ttf"
  done
} > "$out"

echo "wrote $out ($(wc -c < "$out") bytes)"
