#!/usr/bin/env bash
# Regenerate src/glyph_data.inc — the UI glyph font embedded in the executable.
# Run this only when changing which glyphs are bundled; the output is committed.
#
# Needs assets/fonts/PPCGlyphs.ttf (scripts/fetch-glyphs.sh).
set -euo pipefail

root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
fonts="$root/assets/fonts"
out="$root/src/glyph_data.inc"

[ -f "$fonts/PPCGlyphs.ttf" ] || "$root/scripts/fetch-glyphs.sh"

{
  echo "// Generated by scripts/gen-glyph-data.sh — do not edit."
  echo "// A subset of Font Awesome Free Solid, embedded as the TTF bytes themselves."
  echo "// Which codepoints: scripts/fetch-glyphs.sh. What they are called: src/ui/glyphs.hpp."
  echo "// See assets/fonts/README.md for the license this is bundled under."
  echo
  python3 "$root/scripts/bin2c.py" ppc_glyphs_ttf "$fonts/PPCGlyphs.ttf"
} > "$out"

echo "wrote $out ($(wc -c < "$out") bytes)"
